-- Gerado por scripts/generate-catalogo-interface-seed.mjs — não editar à mão.
-- Requer migração 004_catalogo_interface.sql e nó raiz cat_piloto_raiz (seed.sql).

insert into public.catalogo_interface (
  id, stable_code, parent_id, kind, titulo, descricao, ordem,
  page_key, lifecycle_status, metadados
) values
  ('cvi_mod_geral', 'CAT-MOD-GERAL', 'cat_piloto_raiz', 'modulo', 'Visão geral e painéis', 'Módulo do catálogo de interface', 0, null, 'ativo', '{}'::jsonb),
  ('cvi_pg_Home', 'CAT-PG-Home', 'cvi_mod_geral', 'pagina', 'Home', 'Rota: Home', 0, 'Home', 'ativo', '{}'::jsonb),
  ('cvi_pg_Dashboard', 'CAT-PG-Dashboard', 'cvi_mod_geral', 'pagina', 'Dashboard', 'Rota: Dashboard', 1, 'Dashboard', 'ativo', '{}'::jsonb),
  ('cvi_pg_DashboardCaixa', 'CAT-PG-DashboardCaixa', 'cvi_mod_geral', 'pagina', 'Dashboard Caixa', 'Rota: DashboardCaixa', 2, 'DashboardCaixa', 'ativo', '{}'::jsonb),
  ('cvi_pg_DashboardVendedor', 'CAT-PG-DashboardVendedor', 'cvi_mod_geral', 'pagina', 'Dashboard Vendedor', 'Rota: DashboardVendedor', 3, 'DashboardVendedor', 'ativo', '{}'::jsonb),
  ('cvi_pg_PainelGerente', 'CAT-PG-PainelGerente', 'cvi_mod_geral', 'pagina', 'Painel Gerente', 'Rota: PainelGerente', 4, 'PainelGerente', 'ativo', '{}'::jsonb),
  ('cvi_mod_vendas', 'CAT-MOD-VENDAS', 'cat_piloto_raiz', 'modulo', 'Vendas', 'Módulo do catálogo de interface', 1, null, 'ativo', '{}'::jsonb),
  ('cvi_pg_PDV', 'CAT-PG-PDV', 'cvi_mod_vendas', 'pagina', 'PDV', 'Rota: PDV', 0, 'PDV', 'ativo', '{}'::jsonb),
  ('cvi_pg_Vendas', 'CAT-PG-Vendas', 'cvi_mod_vendas', 'pagina', 'Vendas', 'Rota: Vendas', 1, 'Vendas', 'ativo', '{}'::jsonb),
  ('cvi_pg_VendasGestao', 'CAT-PG-VendasGestao', 'cvi_mod_vendas', 'pagina', 'Vendas Gestao', 'Rota: VendasGestao', 2, 'VendasGestao', 'ativo', '{}'::jsonb),
  ('cvi_pg_VendasPerdidas', 'CAT-PG-VendasPerdidas', 'cvi_mod_vendas', 'pagina', 'Vendas Perdidas', 'Rota: VendasPerdidas', 3, 'VendasPerdidas', 'ativo', '{}'::jsonb),
  ('cvi_pg_DevolucaoTroca', 'CAT-PG-DevolucaoTroca', 'cvi_mod_vendas', 'pagina', 'Devolucao Troca', 'Rota: DevolucaoTroca', 4, 'DevolucaoTroca', 'ativo', '{}'::jsonb),
  ('cvi_pg_AutoAtendimento', 'CAT-PG-AutoAtendimento', 'cvi_mod_vendas', 'pagina', 'Auto Atendimento', 'Rota: AutoAtendimento', 5, 'AutoAtendimento', 'ativo', '{}'::jsonb),
  ('cvi_pg_Campanhas', 'CAT-PG-Campanhas', 'cvi_mod_vendas', 'pagina', 'Campanhas', 'Rota: Campanhas', 6, 'Campanhas', 'ativo', '{}'::jsonb),
  ('cvi_pg_TabelasPreco', 'CAT-PG-TabelasPreco', 'cvi_mod_vendas', 'pagina', 'Tabelas Preco', 'Rota: TabelasPreco', 7, 'TabelasPreco', 'ativo', '{}'::jsonb),
  ('cvi_mod_compras', 'CAT-MOD-COMPRAS', 'cat_piloto_raiz', 'modulo', 'Compras e conferência', 'Módulo do catálogo de interface', 2, null, 'ativo', '{}'::jsonb),
  ('cvi_pg_Compras', 'CAT-PG-Compras', 'cvi_mod_compras', 'pagina', 'Compras', 'Rota: Compras', 0, 'Compras', 'ativo', '{}'::jsonb),
  ('cvi_pg_ConferenciaEditor', 'CAT-PG-ConferenciaEditor', 'cvi_mod_compras', 'pagina', 'Conferencia Editor', 'Rota: ConferenciaEditor', 1, 'ConferenciaEditor', 'ativo', '{}'::jsonb),
  ('cvi_pg_ConferenciaEntrada', 'CAT-PG-ConferenciaEntrada', 'cvi_mod_compras', 'pagina', 'Conferencia Entrada', 'Rota: ConferenciaEntrada', 2, 'ConferenciaEntrada', 'ativo', '{}'::jsonb),
  ('cvi_pg_ConferenciaEstoque', 'CAT-PG-ConferenciaEstoque', 'cvi_mod_compras', 'pagina', 'Conferencia Estoque', 'Rota: ConferenciaEstoque', 3, 'ConferenciaEstoque', 'ativo', '{}'::jsonb),
  ('cvi_pg_ConferenciaItens', 'CAT-PG-ConferenciaItens', 'cvi_mod_compras', 'pagina', 'Conferencia Itens', 'Rota: ConferenciaItens', 4, 'ConferenciaItens', 'ativo', '{}'::jsonb),
  ('cvi_pg_ConferenciaVolumes', 'CAT-PG-ConferenciaVolumes', 'cvi_mod_compras', 'pagina', 'Conferencia Volumes', 'Rota: ConferenciaVolumes', 5, 'ConferenciaVolumes', 'ativo', '{}'::jsonb),
  ('cvi_pg_InterfaceSeparador', 'CAT-PG-InterfaceSeparador', 'cvi_mod_compras', 'pagina', 'Interface Separador', 'Rota: InterfaceSeparador', 6, 'InterfaceSeparador', 'ativo', '{}'::jsonb),
  ('cvi_pg_DiscriminarVolumes', 'CAT-PG-DiscriminarVolumes', 'cvi_mod_compras', 'pagina', 'Discriminar Volumes', 'Rota: DiscriminarVolumes', 7, 'DiscriminarVolumes', 'ativo', '{}'::jsonb),
  ('cvi_mod_estoque', 'CAT-MOD-ESTOQUE', 'cat_piloto_raiz', 'modulo', 'Estoque e produtos', 'Módulo do catálogo de interface', 3, null, 'ativo', '{}'::jsonb),
  ('cvi_pg_Estoque', 'CAT-PG-Estoque', 'cvi_mod_estoque', 'pagina', 'Estoque', 'Rota: Estoque', 0, 'Estoque', 'ativo', '{}'::jsonb),
  ('cvi_pg_Produtos', 'CAT-PG-Produtos', 'cvi_mod_estoque', 'pagina', 'Produtos', 'Rota: Produtos', 1, 'Produtos', 'ativo', '{}'::jsonb),
  ('cvi_pg_ImportacaoProdutos', 'CAT-PG-ImportacaoProdutos', 'cvi_mod_estoque', 'pagina', 'Importacao Produtos', 'Rota: ImportacaoProdutos', 2, 'ImportacaoProdutos', 'ativo', '{}'::jsonb),
  ('cvi_pg_AuditoriaEstoque', 'CAT-PG-AuditoriaEstoque', 'cvi_mod_estoque', 'pagina', 'Auditoria Estoque', 'Rota: AuditoriaEstoque', 3, 'AuditoriaEstoque', 'ativo', '{}'::jsonb),
  ('cvi_pg_AuditoriaEstoqueV2', 'CAT-PG-AuditoriaEstoqueV2', 'cvi_mod_estoque', 'pagina', 'Auditoria Estoque V2', 'Rota: AuditoriaEstoqueV2', 4, 'AuditoriaEstoqueV2', 'ativo', '{}'::jsonb),
  ('cvi_pg_OtimizacaoEstoqueIA', 'CAT-PG-OtimizacaoEstoqueIA', 'cvi_mod_estoque', 'pagina', 'Otimizacao Estoque IA', 'Rota: OtimizacaoEstoqueIA', 5, 'OtimizacaoEstoqueIA', 'ativo', '{}'::jsonb),
  ('cvi_pg_EditarProdutosEmMassa', 'CAT-PG-EditarProdutosEmMassa', 'cvi_mod_estoque', 'pagina', 'Editar Produtos Em Massa', 'Rota: EditarProdutosEmMassa', 6, 'EditarProdutosEmMassa', 'ativo', '{}'::jsonb),
  ('cvi_pg_EdicaoMassivaCustos', 'CAT-PG-EdicaoMassivaCustos', 'cvi_mod_estoque', 'pagina', 'Edicao Massiva Custos', 'Rota: EdicaoMassivaCustos', 7, 'EdicaoMassivaCustos', 'ativo', '{}'::jsonb),
  ('cvi_pg_EstimativaEmbalagensIA', 'CAT-PG-EstimativaEmbalagensIA', 'cvi_mod_estoque', 'pagina', 'Estimativa Embalagens IA', 'Rota: EstimativaEmbalagensIA', 8, 'EstimativaEmbalagensIA', 'ativo', '{}'::jsonb),
  ('cvi_pg_ExclusaoDocumentos', 'CAT-PG-ExclusaoDocumentos', 'cvi_mod_estoque', 'pagina', 'Exclusao Documentos', 'Rota: ExclusaoDocumentos', 9, 'ExclusaoDocumentos', 'ativo', '{}'::jsonb),
  ('cvi_mod_financeiro', 'CAT-MOD-FINANCEIRO', 'cat_piloto_raiz', 'modulo', 'Financeiro e caixa', 'Módulo do catálogo de interface', 4, null, 'ativo', '{}'::jsonb),
  ('cvi_pg_Financeiro', 'CAT-PG-Financeiro', 'cvi_mod_financeiro', 'pagina', 'Financeiro', 'Rota: Financeiro', 0, 'Financeiro', 'ativo', '{}'::jsonb),
  ('cvi_pg_FinanceiroModulo', 'CAT-PG-FinanceiroModulo', 'cvi_mod_financeiro', 'pagina', 'Financeiro Modulo', 'Rota: FinanceiroModulo', 1, 'FinanceiroModulo', 'ativo', '{}'::jsonb),
  ('cvi_pg_FinanceiroAprovacoes', 'CAT-PG-FinanceiroAprovacoes', 'cvi_mod_financeiro', 'pagina', 'Financeiro Aprovacoes', 'Rota: FinanceiroAprovacoes', 2, 'FinanceiroAprovacoes', 'ativo', '{}'::jsonb),
  ('cvi_pg_FluxoCaixa', 'CAT-PG-FluxoCaixa', 'cvi_mod_financeiro', 'pagina', 'Fluxo Caixa', 'Rota: FluxoCaixa', 3, 'FluxoCaixa', 'ativo', '{}'::jsonb),
  ('cvi_pg_ContasFinanceiras', 'CAT-PG-ContasFinanceiras', 'cvi_mod_financeiro', 'pagina', 'Contas Financeiras', 'Rota: ContasFinanceiras', 4, 'ContasFinanceiras', 'ativo', '{}'::jsonb),
  ('cvi_pg_ExtratoConta', 'CAT-PG-ExtratoConta', 'cvi_mod_financeiro', 'pagina', 'Extrato Conta', 'Rota: ExtratoConta', 5, 'ExtratoConta', 'ativo', '{}'::jsonb),
  ('cvi_pg_LancamentoAnexos', 'CAT-PG-LancamentoAnexos', 'cvi_mod_financeiro', 'pagina', 'Lancamento Anexos', 'Rota: LancamentoAnexos', 6, 'LancamentoAnexos', 'ativo', '{}'::jsonb),
  ('cvi_pg_Agefin', 'CAT-PG-Agefin', 'cvi_mod_financeiro', 'pagina', 'Agefin', 'Rota: Agefin', 7, 'Agefin', 'ativo', '{}'::jsonb),
  ('cvi_pg_AtualizarBoletoRecorrente', 'CAT-PG-AtualizarBoletoRecorrente', 'cvi_mod_financeiro', 'pagina', 'Atualizar Boleto Recorrente', 'Rota: AtualizarBoletoRecorrente', 8, 'AtualizarBoletoRecorrente', 'ativo', '{}'::jsonb),
  ('cvi_pg_TurnosFechados', 'CAT-PG-TurnosFechados', 'cvi_mod_financeiro', 'pagina', 'Turnos Fechados', 'Rota: TurnosFechados', 9, 'TurnosFechados', 'ativo', '{}'::jsonb),
  ('cvi_pg_CaixasAtivos', 'CAT-PG-CaixasAtivos', 'cvi_mod_financeiro', 'pagina', 'Caixas Ativos', 'Rota: CaixasAtivos', 10, 'CaixasAtivos', 'ativo', '{}'::jsonb),
  ('cvi_pg_ControleCaixasAtivos', 'CAT-PG-ControleCaixasAtivos', 'cvi_mod_financeiro', 'pagina', 'Controle Caixas Ativos', 'Rota: ControleCaixasAtivos', 11, 'ControleCaixasAtivos', 'ativo', '{}'::jsonb),
  ('cvi_pg_PDVAuditoria', 'CAT-PG-PDVAuditoria', 'cvi_mod_financeiro', 'pagina', 'PDV Auditoria', 'Rota: PDVAuditoria', 12, 'PDVAuditoria', 'ativo', '{}'::jsonb),
  ('cvi_mod_logistica', 'CAT-MOD-LOGISTICA', 'cat_piloto_raiz', 'modulo', 'Logística', 'Módulo do catálogo de interface', 5, null, 'ativo', '{}'::jsonb),
  ('cvi_pg_HubLogistico', 'CAT-PG-HubLogistico', 'cvi_mod_logistica', 'pagina', 'Hub Logistico', 'Rota: HubLogistico', 0, 'HubLogistico', 'ativo', '{}'::jsonb),
  ('cvi_pg_Expedicao', 'CAT-PG-Expedicao', 'cvi_mod_logistica', 'pagina', 'Expedicao', 'Rota: Expedicao', 1, 'Expedicao', 'ativo', '{}'::jsonb),
  ('cvi_pg_Veiculos', 'CAT-PG-Veiculos', 'cvi_mod_logistica', 'pagina', 'Veiculos', 'Rota: Veiculos', 2, 'Veiculos', 'ativo', '{}'::jsonb),
  ('cvi_pg_ControleEntregas', 'CAT-PG-ControleEntregas', 'cvi_mod_logistica', 'pagina', 'Controle Entregas', 'Rota: ControleEntregas', 3, 'ControleEntregas', 'ativo', '{}'::jsonb),
  ('cvi_pg_Armazenagem', 'CAT-PG-Armazenagem', 'cvi_mod_logistica', 'pagina', 'Armazenagem', 'Rota: Armazenagem', 4, 'Armazenagem', 'ativo', '{}'::jsonb),
  ('cvi_pg_ReimpressaoDocumentos', 'CAT-PG-ReimpressaoDocumentos', 'cvi_mod_logistica', 'pagina', 'Reimpressao Documentos', 'Rota: ReimpressaoDocumentos', 5, 'ReimpressaoDocumentos', 'ativo', '{}'::jsonb),
  ('cvi_mod_config', 'CAT-MOD-CONFIG', 'cat_piloto_raiz', 'modulo', 'Configuração e cadastros', 'Módulo do catálogo de interface', 6, null, 'ativo', '{}'::jsonb),
  ('cvi_pg_Configuracoes', 'CAT-PG-Configuracoes', 'cvi_mod_config', 'pagina', 'Configuracoes', 'Rota: Configuracoes', 0, 'Configuracoes', 'ativo', '{}'::jsonb),
  ('cvi_pg_Terceiros', 'CAT-PG-Terceiros', 'cvi_mod_config', 'pagina', 'Terceiros', 'Rota: Terceiros', 1, 'Terceiros', 'ativo', '{}'::jsonb),
  ('cvi_pg_Intervenientes', 'CAT-PG-Intervenientes', 'cvi_mod_config', 'pagina', 'Intervenientes', 'Rota: Intervenientes', 2, 'Intervenientes', 'ativo', '{}'::jsonb),
  ('cvi_pg_Operacoes', 'CAT-PG-Operacoes', 'cvi_mod_config', 'pagina', 'Operacoes', 'Rota: Operacoes', 3, 'Operacoes', 'ativo', '{}'::jsonb),
  ('cvi_pg_Manual', 'CAT-PG-Manual', 'cvi_mod_config', 'pagina', 'Manual', 'Rota: Manual', 4, 'Manual', 'ativo', '{}'::jsonb),
  ('cvi_pg_MapaFuncionalidades', 'CAT-PG-MapaFuncionalidades', 'cvi_mod_config', 'pagina', 'Mapa Funcionalidades', 'Rota: MapaFuncionalidades', 5, 'MapaFuncionalidades', 'ativo', '{}'::jsonb),
  ('cvi_pg_LogsAutenticacao', 'CAT-PG-LogsAutenticacao', 'cvi_mod_config', 'pagina', 'Logs Autenticacao', 'Rota: LogsAutenticacao', 6, 'LogsAutenticacao', 'ativo', '{}'::jsonb),
  ('cvi_pg_AnexoCompartilhado', 'CAT-PG-AnexoCompartilhado', 'cvi_mod_config', 'pagina', 'Anexo Compartilhado', 'Rota: AnexoCompartilhado', 7, 'AnexoCompartilhado', 'ativo', '{}'::jsonb),
  ('cvi_mod_relatorios', 'CAT-MOD-RELATORIOS', 'cat_piloto_raiz', 'modulo', 'Relatórios', 'Módulo do catálogo de interface', 7, null, 'ativo', '{}'::jsonb),
  ('cvi_pg_Relatorios', 'CAT-PG-Relatorios', 'cvi_mod_relatorios', 'pagina', 'Relatorios', 'Rota: Relatorios', 0, 'Relatorios', 'ativo', '{}'::jsonb),
  ('cvi_pg_RelatorioMargem', 'CAT-PG-RelatorioMargem', 'cvi_mod_relatorios', 'pagina', 'Relatorio Margem', 'Rota: RelatorioMargem', 1, 'RelatorioMargem', 'ativo', '{}'::jsonb),
  ('cvi_pg_RelatorioPerformance', 'CAT-PG-RelatorioPerformance', 'cvi_mod_relatorios', 'pagina', 'Relatorio Performance', 'Rota: RelatorioPerformance', 2, 'RelatorioPerformance', 'ativo', '{}'::jsonb)
on conflict (id) do nothing;