const fs = require("fs");
const path = require("path");
const p = path.join(__dirname, "../src/components/vendas/PDVVendedor.jsx");
let c = fs.readFileSync(p, "utf8");
const old1 = "import { Search, ShoppingCart, Trash2, UserPlus, ArrowRight, Barcode, Truck, Store, Keyboard, Plus, Minus, ArrowLeft, ChevronDown, ChevronRight, AlertCircle, Package, Camera, Undo2, X, Edit, FileText, CreditCard } from 'lucide-react';";
const new1 = "import { Search, ShoppingCart, Trash2, UserPlus, ArrowRight, Barcode, Truck, Store, Keyboard, Plus, Minus, ArrowLeft, ChevronDown, ChevronRight, AlertCircle, Package, Boxes, Camera, Undo2, X, Edit, FileText, CreditCard } from 'lucide-react';";
if (!c.includes(old1)) throw new Error("lucide import not found");
c = c.replace(old1, new1);
const old2 = "import { buildSaleUnitOptions, calculateBaseQuantity, getItemUnitKey } from '@/lib/productUnits';";
const new2 = "import { buildSaleUnitOptions, calculateBaseQuantity, getItemUnitKey, pickDefaultSaleUnit } from '@/lib/productUnits';";
if (!c.includes(old2)) throw new Error("productUnits import not found");
c = c.replace(old2, new2);
const old3 = "    const opcoes = buildSaleUnitOptions(produto, tabelaPreco?.fator_ajuste || 1);\r\n    if (opcoes.length > 1) {\r\n      setUnitSelector({ open: true, product: produto });\r\n      return;\r\n    }\r\n\r\n    aplicarUnidadeAoProdutoSelecionado(produto, opcoes[0]);";
const new3 = "    const mult = tabelaPreco?.fator_ajuste || 1;\r\n    const opcoes = buildSaleUnitOptions(produto, mult);\r\n    const defaultOpt = pickDefaultSaleUnit(produto, mult);\r\n\r\n    if (opcoes.length > 1) {\r\n      aplicarUnidadeAoProdutoSelecionado(produto, defaultOpt || opcoes[0]);\r\n      return;\r\n    }\r\n\r\n    aplicarUnidadeAoProdutoSelecionado(produto, opcoes[0]);";
if (!c.includes(old3)) throw new Error("handleSelecionarProduto block not found");
c = c.replace(old3, new3);
fs.writeFileSync(p, c, "utf8");
console.log("OK imports+handler");
